# Generated by Django 3.0.8 on 2020-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='order_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
