# Generated by Django 3.0.8 on 2020-07-09 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200704_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_no',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
