# Generated by Django 3.0.8 on 2020-07-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200711_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
