# Generated by Django 3.0.8 on 2020-08-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200724_2152'),
        ('product', '0006_auto_20200711_1653'),
    ]

    operations = [
    ]
