# Generated by Django 3.0.8 on 2020-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_merge_20200803_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='order_no',
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=250),
        ),
    ]
