# Generated by Django 3.0.8 on 2020-08-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200807_2047'),
        ('product', '0009_auto_20200807_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childer', to='myapp.UserDetails'),
        ),
    ]
