# Generated by Django 3.0.6 on 2020-07-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='gender',
        ),
    ]
