# Generated by Django 3.0.6 on 2020-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
