# Generated by Django 3.0.8 on 2020-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200724_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
